[package]
name = "win_partiotions"
version = "0.1.0"
authors = ["Ali <a.shahi21294@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.18.0"

[build-dependencies]
windows = "0.18.0"
